### ISSUE TITLE
Give guidance for identities when using session resumption

### ISSUE THREAD

**Issue by alandekok** [emu-wg/draft-ietf-emu-eap-tls13#11]
As discussed on the EMU list.  Section 2.1.2 should be updated to add something like:

The EAP Identity used in resumption SHOULD be the same EAP Identity as was used during the original authentication.  This requirement allows EAP packets to be routable through an AAA infrastructure to the same destination as the original authentication.

The alternative is to derive the EAP Identity from the identity used inside of TLS.  This derivation is common practice when using certificates, and works because the "common name" field in the certificate is typically compatible with EAP, and it contains a routable identifier such as an email address.  This practice cannot be used for resumption, as the PSK identity may be a binary blob, and it might not contain a routable realm as suggested by RFC 7542.

In some cases, the PSK identity is derived by the underlying TLS implementation, and cannot be controlled by the EAP authenticator.  These limitations make the PSK identity unsuitable for use as the EAP Identity.

**Comment by jsalowey** [comment]
I think NAI should be used instead of EAP identity.  

If we are going to talk about deriving the NAI from the common name then we should be specific that an anonymous NAI consisting of only the domain portion of the common name.  Likewise a PSK identity may be of a form of an NAI which can be used to derive an anonymous NAI. Implementations should provide a way to override this behavior int he case that the certificate identity or PSK identity is not usable for this purpose.

Text like this could be added to the privacy section where NAI is described.

**Comment by alandekok** [comment]
> I think NAI should be used instead of EAP identity.

I mostly agree.  My phrasing is trying to allow non-NAIs in some cases.

i.e. the recommendation is to use the anonymized NAI pretty much always.  Then as a special call-out for resumption, require the *same* Identity as for the original authentication.  Whatever that is.

I would prefer to have a separate section about identities.  I find the current text a bit unclear.  It helps to explain why we're recommending an anonymized NAI, when there are no certificates.

**Comment by emanjon** [comment]
Added text based on these suggestions in draft-ietf-emu-eap-tls13-08
