### ISSUE TITLE
Clarify NAI handling

### ISSUE THREAD

**Issue by jsalowey** [emu-wg/draft-ietf-emu-eap-tls13#61]
From Alan's review:
Section 2.1.3 says:

   It is RECOMMENDED to use a Network Access Identifiers (NAIs) with the
   same realm in the resumption and the original full handshake.

As discussed further in 2.1.3, not following this suggestion creates
difficulties.  The later text gives a recommendation, but this
recommendation is likely not strong enough.

Specifically, there is no reason to use different identities for full
authentication and for resumption.  The TLS PSK identity used for
resumption can (and should) be independent of the identity given in
the EAP Identity Response.

Perhaps the best thing is to make this suggestion a MUST:

   When resumption is use, the value of the EAP Identity Response MUST
   be the same as used in the original full authentication.
 
Section 2.1.3 continues with the same subject:

   When NAI reuse can
   be done without privacy implications, it is RECOMMENDED to use the
   same anonymous NAI in the resumption, as was used in the original
   full handshake [RFC7542]

Based on recent investigation into EAP / TLS / resumption, this
recommendation should be changed to a MUST:

   When resumption is use, the value of the EAP Identity Response MUST
   be the same as used in the original full authentication.  This
   reuse means that the issues of identy privacy are the same for full
   authentication and resumption.

Section 2.1.3 says:

   ... For example, the NAI @realm can safely be
   reused since it does not provide any specific information to
   associate a user's resumption attempt with the original full
   handshake.  However, reusing the NAI
   P2ZIM2F+OEVAO21nNWg2bVpgNnU=@realm enables an on-path attacker to
   associate a resumption attempt with the original full handshake. 

On-path attackers can access significantly more information than the
identity.  This information includes things like MAC address of end
device, which even with MAC address randomization, typically only
changes once a day.  It may be good to explain that attackers may have
access to other information, but also that it is beneficial to
minimize the amount of identification information that an attacker
has.  Section 5 has more dicussion on this topic, which could perhaps
be used here.

Section 2.1.3 says:

   ... The
   TLS PSK identity is typically derived by the TLS implementation and
   may be an opaque blob without a routable realm.  The TLS PSK identity
   is therefore in general unsuitable for deriving a NAI to use in the
   Identity Response.

This comment states what should not be done, but it gives no
recommendations for what should be done.  It is also not clear why an
EAP peer would "derive" an NAI from the Identity Response.  Would the
EAP peer not simply use the TLS PSK identity verbatim in the Identity
Response for the next authentication?  Or, would the EAP peer simply
not re-use the same identity as for the original full authentication?

These questions are addressed by simply requiring re-use of the EAP
Identity Response from the original full authentication.

**Comment by ms-s** [comment]
@alandekok and @jsalowey : The text carefully puts recommendations on using the the same realm and not the same NAI/Identity-Response. Mandating use of the same NAI will forbid all encrypted identities. 5G Subscription Concealed Identifier (SUCI) is an example of an encrypted identifier. It is different for each invocation. For encrypted identifiers like SUCI, the username part can (and should) be different between resumption and full handshake. It is important for the realm to remain the same for routing EAP authentication to the original server. The text does not use a MUST for using the same realm since at least I am aware of implementations where the server assigns a new realm after successful initial authentication. Later, during resumption, the peer uses the new realm assigned by the server. I suspect we might see more such scenarios in the IoT ecosystem (cc: @elear) where the manufacturer does the initial authentication and assigns a new realm for the new owner which the peer should use during the subsequent resumptions.

How about a slightly modified version: It is RECOMMENDED to use a Network Access Identifiers (NAIs) with the same realm during resumption and the original full handshake. This requirement allows EAP packets to be routed to the same destination as the original full handshake.  If this recommendation is not followed, resumption is likely impossible.  When NAI reuse can be done without privacy implications, it is RECOMMENDED to use the same NAI in the resumption, as was used in the original full handshake [RFC7542].  For example, the NAI @realm can safely be reused since it does not provide any specific information to associate a user's resumption attempt with the original full handshake.  However, reusing the NAI P2ZIM2F+OEVAO21nNWg2bVpgNnU=@realm enables an on-path attacker to associate a resumption attempt with the original full handshake.  The TLS PSK identity is typically derived by the TLS implementation and may be an opaque blob without a routable realm. The TLS PSK identity on its own is therefore unsuitable as a NAI in the Identity Response.

**Comment by alandekok** [comment]
OK, so the global `MUST` here is too strong.  The suggested text seems fine

**Comment by elear** [comment]
This should probably go to the EMU list.  There may be uses where a tear down and reauthentication is quite expensive, and that therefore, resumption might be desirable after an NAI realm is provisioned, but that would take quite a lot of mechanism to get right.

**Comment by ms-s** [comment]
@elear: I don't think this specification is the right place to define provisioning of new realms. We just don't want to forbid the possibility by mandating something else. We are not really changing the text that already exists in the draft.

**Comment by ms-s** [comment]
5f5270b has hopefully resolved this issue.

**Comment by elear** [comment]
@ms-s I'm not saying it is.  I'm just responding to the point you raised: "the manufacturer does the initial authentication and assigns a new realm for the new owner which the peer should use during the subsequent resumptions."

**Comment by ms-s** [comment]
I understand. Hopefully it is okay that this issue is now marked as closed. 

As you can imagine, I am eager to get this document finished. I don't want to compromise the document quality, but as they say, "perfection is enemy of progress".
