### ISSUE TITLE
What is limited authorization?

### ISSUE THREAD

**Issue by jsalowey** [emu-wg/draft-ietf-emu-eap-tls13#62]
From alan's review

> Section 5.4 says:
> 
>    An implementation MAY enforce limited authorization before revocation
>    checking has been done.
> 
> Question: an implementation of what?  The EAP peer?  EAP server?
> RADIUS server?  What does "limited authorization" look like in practice?
> 
>

**Comment by jsalowey** [comment]
@ms-s @emanjon Can you clarify what this means?  Is this what is intended? 

"A peer implementation MAY limit network communication until it performs revocation checking."

**Comment by ms-s** [comment]
@jsalowey your suggestion looks good. @alandekok is the suggestion from Joe okay for you?

**Comment by alandekok** [comment]
I'm not sure what "limit network communication" means.  Perhaps a bit more description.  https://tools.ietf.org/html/rfc6108#section-12 discusses a "walled garden", but we probably don't want to reference that here.  Perhaps instead just rephrasing some of that text in a way that's more applicable to this use-case.

**Comment by ms-s** [comment]
Not sure I understand. This is not about restricting the EAP peer in some walled garden. Rather, the text is trying to say that the peer should not trust the network (and any services) even though it has received an EAP-Success and network connectivity because the revocation status of the server certificate has not been verified yet. Perhaps the sentence could be "An EAP peer implementation SHOULD not trust the network (and any services) until it has verified the revocation status of the server certificate after receiving connectivity is available"?

We can get also get rid of this sentence completely? RFC5216 only said this " To enable revocation checking in situations where servers do not support Certificate Status Request messages and network connectivity is not available prior to authentication completion, peer implementations MUST also support checking for certificate revocation after authentication completes and network connectivity is available, and they SHOULD utilize this capability by default.". Adding more sentences is not necessarily always beneficial.

**Comment by alandekok** [comment]
The text is a little confusing then.  We don't typically talk about clients "enforcing limited authorization".  Only servers / APs / NASes enforce authorization.

I think your suggestion is good, I would just add a minor point:

```
An EAP peer implementation SHOULD NOT trust the network (and any services) until it has verified the revocation status of the server certificate after receiving network connectivity.  As the underlying network is not trusted, the EAP peer MUST use a secure transport such as TLS in order to verify the revocation status of the server certificate.  The EAP peer also SHOULD NOT send any traffic other than necessary to perform revocation checking, until such time as the revocation checks have finished.
```

**Comment by ms-s** [comment]
ad67110 should address this
